# Site settings
title: 'Karrah &amp; Kyle'
baseurl: ''
distbase: '/dist'
imagebase: '/dist/images'
wedding_date: 'January 29th, 2022'
wedding_location: 'St. John, USVI'
production_url: 'https://karrahandkyle.com'

# Build settings
permalink: pretty
exclude: [
  'node_modules',
  'package.json',
  'package-lock.json',
  'gulpfile.js',
  'README.md',
  'SOURCE',
  'assets/'
]
languages: ['en']
